/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.net.ServerSocket;
import java.net.Socket;

public class App{
    public static void main(String args[])throws Exception{  
        if (args.length < 1) return;
        int port = Integer.parseInt(args[0]);

        ServerSocket ss = new ServerSocket(port);  
        Socket s = ss.accept();  

        try{
            // Socket s = ss.accept();
            WriteThread writer = new WriteThread(s);// str=din.readUTF(); 
            ReadThread reader = new ReadThread(s);
            writer.start(); 
            reader.start();
        }catch (Exception ex){
            System.out.println("Error :" + ex);
        }
        ss.close();   
    }
}
